const concepts = [
  ["01","editorial","Editorial atlas","A calm destination map where geography supports a story, not a dashboard.","Apple Maps Guides"],
  ["02","terrain","Immersive terrain","Tilted topography and landmark depth make an unfamiliar landscape legible.","Mapbox Standard 3D"],
  ["03","heat","Trail pulse","Popularity, quietness, and weather overlays help decide when and where to go.","AllTrails overlays"],
  ["04","layers","Shared field map","Pins, notes, routes, and areas turn the map into a collaborative planning canvas.","Felt annotations"],
  ["05","replay","Journey replay","A moving route connects travel steps, dates, photos, and transport modes.","Polarsteps route replay"],
  ["06","planner","Day route planner","Ordered stops, route modes, and daily distances make an itinerary actionable.","Wanderlog · Komoot"],
  ["07","highlights","Community highlights","Photo-led recommendations reveal memorable places and route segments.","Komoot Highlights"],
  ["08","time","Time-aware preview","A time slider previews light, weather, and crowd conditions before committing.","Google Immersive View"],
  ["09","compare","Map compare","A swipe divider compares saved inspiration with visited history in one geography.","Layer comparison tools"],
  ["10","mobile","Explore this area","A mobile map pairs direct manipulation with contextual categories and results.","Airbnb map search"],
];

const sources = [
  ["Mapbox Standard","3D buildings, terrain, landmarks, and dynamic lighting","https://docs.mapbox.com/map-styles/reference/standard/"],
  ["AllTrails","Community heatmap, precipitation, and temperature overlays","https://support.alltrails.com/hc/en-us/articles/37228180990228-AllTrails-map-types-overlays-and-extras"],
  ["Felt","Collaborative pins, notes, routes, areas, and layer controls","https://help.felt.com/annotations/annotations"],
  ["Komoot","Community Highlights and waypoint-based route planning","https://support.komoot.com/hc/en-us/articles/360058904532-Highlights-displayed-on-the-map"],
  ["Polarsteps","Trip routes, travel steps, and replayable journey maps","https://www.polarsteps.com/"],
  ["Google Maps","Immersive route previews with time and weather context","https://blog.google/products-and-platforms/products/maps/google-maps-october-2023-update/"],
];

const grid = document.querySelector("#grid");
const toast = document.querySelector("#toast");
const states = new Map();
let toastTimer;
const icon = (name, size=16) => `<i data-lucide="${name}" width="${size}" height="${size}" aria-hidden="true"></i>`;

function mapSvg(extra="") {
  return `<svg class="map-art" viewBox="0 0 600 400" preserveAspectRatio="none" aria-hidden="true"><path class="water" d="M-20 320C90 235 138 333 240 285s167-20 220-89 122-49 171-88v320H-20Z"/><path class="park" d="M44 40c74-42 150 0 125 69s-75 96-134 55S-5 68 44 40Z"/><path class="road major" d="M-20 88C103 122 144 207 262 205s159-94 367-50"/><path class="road" d="M91-30c13 110 92 143 73 241s55 159 38 228"/><path class="road" d="M342-20c-22 92 48 121 42 209s-71 131-63 244"/><path class="road fine" d="M-10 250c114-31 184 22 267 72s209 4 370 24"/>${extra}</svg>`;
}

function pins(labels=["Path of the Gods","Positano","Lago di Sorapis","Cortina"]) {
  return labels.map((label,index)=>`<button class="pin p${index+1}" data-place="${label}" type="button"><i></i><span>${label}</span></button>`).join("");
}

const renderers = {
  editorial: () => `<div class="map editorial-map">${mapSvg()}${pins()}<div class="map-title"><small>Campania · Italy</small><b>The Amalfi edit</b><span>12 places saved from 8 stories</span></div><article class="editor-card"><div></div><small>Editor’s route · 01</small><b>Path of the Gods</b><p>Start in Bomerano before the coast wakes up.</p><button data-action="next" type="button">Next place ${icon("arrow-right",14)}</button></article></div>`,
  terrain: (s={tilted:true}) => `<div class="map terrain-map ${s.tilted?"is-tilted":""}">${mapSvg('<path class="contour" d="M30 160c80-80 196-75 240 12s121 106 284 43"/><path class="contour c2" d="M8 130c111-105 260-80 294 13s133 113 297 25"/>')}<div class="mountain m1"></div><div class="mountain m2"></div>${pins(["Tre Cime","Lago di Sorapis","Rifugio Vandelli"])}<div class="terrain-tools"><button data-action="tilt" type="button">${icon("box",14)} ${s.tilted?"2D":"3D"}</button><button data-action="landmarks" type="button">${icon("building-2",14)} Landmarks</button></div><div class="elevation"><span>1,698 m</span><i></i><b>2,405 m</b></div></div>`,
  heat: (s={layer:"popular"}) => `<div class="map heat-map layer-${s.layer}">${mapSvg()}<div class="heat h1"></div><div class="heat h2"></div><div class="heat h3"></div>${pins(["Popular ridge","Quiet trail","Lake access"])}<nav class="layer-tabs">${[["popular","flame","Popular"],["quiet","leaf","Quiet"],["rain","cloud-rain","Rain"],["temp","thermometer","Temp"]].map(([id,ic,label])=>`<button class="${s.layer===id?"active":""}" data-layer="${id}" type="button">${icon(ic,13)}${label}</button>`).join("")}</nav><div class="heat-legend"><span>Low</span><i></i><span>High</span></div></div>`,
  layers: (s={tool:"pin",notes:1}) => `<div class="map layers-map">${mapSvg('<path class="drawn-route" d="M92 278C163 232 240 254 304 181s130-59 207-88"/>')}<div class="drawn-area"></div>${pins(["Hotel","Dinner","Sunrise"])}${Array.from({length:s.notes},(_,i)=>`<button class="map-note note-${i+1}" data-place="Trip note" type="button">${icon("message-square",13)}<span>${i?"Meet here":"Great sunset"}</span></button>`).join("")}<nav class="draw-tools">${[["pin","map-pin"],["note","sticky-note"],["route","route"],["area","pentagon"],["layers","layers-3"]].map(([id,ic])=>`<button class="${s.tool===id?"active":""}" data-tool="${id}" type="button">${icon(ic,15)}</button>`).join("")}</nav><div class="people"><span>AV</span><span>MK</span><b>2 planning</b></div></div>`,
  replay: (s={step:0,playing:false}) => { const stops=["Rome","Florence","Venice","Dolomites"]; return `<div class="map replay-map">${mapSvg('<path class="trip-line" d="M78 315C152 276 166 224 249 238s84-98 164-73 74-60 116-98"/>')}${stops.map((stop,i)=>`<button class="trip-stop s${i+1} ${i<=s.step?"passed":""}" data-step="${i}" type="button"><i>${i+1}</i><span>${stop}</span></button>`).join("")}<article class="replay-card"><small>Day ${s.step*2+1} · ${["Train","Walk","Boat","Hike"][s.step]}</small><b>${stops[s.step]}</b><span>${["May 12","May 14","May 16","May 18"][s.step]}</span></article><div class="replay-controls"><button data-action="play" type="button">${icon(s.playing?"pause":"play",14)}</button><input data-replay type="range" min="0" max="3" value="${s.step}"/><span>${s.step+1}/4</span></div></div>`; },
  planner: (s={day:1,mode:"walk"}) => { const dayStops={1:["Duomo","Uffizi","Santo Spirito"],2:["Fiesole","Mercato Centrale","Santa Croce"],3:["Siena","Monteriggioni","Chianti"]}[s.day]; return `<div class="planner-shell"><aside><header><small>Italy · 7 days</small><b>Day ${s.day} in Tuscany</b></header><nav>${[1,2,3].map(d=>`<button class="${s.day===d?"active":""}" data-day="${d}" type="button">D${d}</button>`).join("")}</nav><ol>${dayStops.map((stop,i)=>`<li><i>${i+1}</i><span><b>${stop}</b><small>${9+i*3}:00 · ${i?"1.8 km":"Start"}</small></span></li>`).join("")}</ol><div class="modes">${[["walk","person-standing"],["drive","car"],["bike","bike"]].map(([id,ic])=>`<button class="${s.mode===id?"active":""}" data-mode="${id}" type="button">${icon(ic,13)}</button>`).join("")}</div></aside><div class="map">${mapSvg('<path class="day-route" d="M105 286C175 244 241 296 288 198s122-43 194-117"/>')}${dayStops.map((stop,i)=>`<button class="pin p${i+1}" data-place="${stop}" type="button"><i>${i+1}</i><span>${stop}</span></button>`).join("")}<div class="route-stat"><b>${s.mode==="drive"?"42 min":s.mode==="bike"?"1h 12":"3h 20"}</b><span>12.4 km · 3 stops</span></div></div></div>`; },
  highlights: (s={filter:"all"}) => `<div class="map highlight-map">${mapSvg()}${[["view","Path of the Gods","p1"],["food","Da Adolfo","p2"],["swim","Fiordo di Furore","p3"]].filter(([type])=>s.filter==="all"||s.filter===type).map(([type,name,pos])=>`<button class="photo-pin ${pos}" data-place="${name}" type="button"><span class="photo ${type}"></span><b>${name}</b><small>${type} · recommended</small></button>`).join("")}<nav class="highlight-filters">${["all","view","food","swim"].map(id=>`<button class="${s.filter===id?"active":""}" data-filter="${id}" type="button">${id}</button>`).join("")}</nav><div class="highlight-copy"><span>${icon("sparkles",13)} 14 community highlights</span><b>Worth a detour</b></div></div>`,
  time: (s={hour:8}) => { const phase=s.hour<10?"morning":s.hour<17?"day":"dusk"; return `<div class="map time-map ${phase}">${mapSvg()}${pins(["Path of the Gods","Nocelle","Positano"])}<div class="sun"></div><article><small>${String(s.hour).padStart(2,"0")}:00 · ${phase}</small><b>${s.hour<10?"Cool and quiet":s.hour<17?"Bright and busy":"Golden and easing"}</b><div><span>${icon("thermometer",12)} ${14+Math.abs(12-s.hour)}°</span><span>${icon("users",12)} ${s.hour<9?"Low":s.hour<17?"High":"Medium"}</span><span>${icon("cloud-sun",12)} Clear</span></div></article><div class="time-slider"><span>06:00</span><input data-time type="range" min="6" max="20" value="${s.hour}"/><span>20:00</span></div></div>`; },
  compare: (s={split:50}) => `<div class="map compare-map">${mapSvg()}<div class="compare-layer visited" style="clip-path:inset(0 ${100-s.split}% 0 0)">${pins(["Rome","Florence","Venice"])}</div><div class="compare-layer saved" style="clip-path:inset(0 0 0 ${s.split}%)">${pins(["Sorapis","Amalfi","Siena"])}</div><div class="divider" style="left:${s.split}%"><i></i></div><input aria-label="Compare saved and visited maps" data-compare type="range" min="15" max="85" value="${s.split}"/><div class="compare-label left">Visited · 24</div><div class="compare-label right">Saved · 37</div></div>`,
  mobile: (s={category:"all",open:false}) => `<div class="mobile-stage"><div class="phone-map map">${mapSvg()}${pins(["Path of the Gods","Amalfi","Ravello","Furore"])}<button class="search-area" data-action="search" type="button">${icon("refresh-cw",12)} Search this area</button><div class="mobile-search">${icon("search",14)}<span>Amalfi Coast</span>${icon("sliders-horizontal",14)}</div><div class="category-row">${["all","views","food","beaches"].map(id=>`<button class="${s.category===id?"active":""}" data-category="${id}" type="button">${id}</button>`).join("")}</div><section class="result-sheet ${s.open?"open":""}"><button data-action="sheet" type="button"><i></i><b>12 places nearby</b><span>${s.open?"Collapse":"See list"}</span></button><div><article><div></div><span><small>Hike · 8 saves</small><b>Path of the Gods</b><em>4.9 ★</em></span></article><article><div></div><span><small>Beach · 5 saves</small><b>Fiordo di Furore</b><em>4.7 ★</em></span></article></div></section></div></div>`,
};

function initial(slug){ return ({terrain:{tilted:true},heat:{layer:"popular"},layers:{tool:"pin",notes:1},replay:{step:0,playing:false},planner:{day:1,mode:"walk"},highlights:{filter:"all"},time:{hour:8},compare:{split:50},mobile:{category:"all",open:false}})[slug]||{}; }
concepts.forEach(([,slug])=>states.set(slug,initial(slug)));

function render(slug){ const root=grid.querySelector(`[data-stage="${slug}"]`); if(root){ root.innerHTML=renderers[slug](states.get(slug)); lucide.createIcons(); } }
grid.innerHTML=concepts.map(([id,slug,name,note,cue])=>`<article class="demo concept-${slug}" data-demo="${slug}"><header><span>${id}</span><div><h3>${name}</h3><p>${note}</p><small>Research cue · ${cue}</small></div><button data-reset type="button" aria-label="Reset ${name}">${icon("rotate-ccw",14)}</button></header><div class="stage" data-stage="${slug}"></div></article>`).join("");
concepts.forEach(([,slug])=>render(slug));
document.querySelector("#sources").innerHTML=sources.map(([name,note,url])=>`<a href="${url}" target="_blank" rel="noreferrer"><b>${name}</b><span>${note}</span></a>`).join("");

function patch(slug,next){ states.set(slug,{...states.get(slug),...next}); render(slug); }
function notify(message){ clearTimeout(toastTimer); toast.textContent=message; toast.hidden=false; toastTimer=setTimeout(()=>toast.hidden=true,1600); }
grid.addEventListener("click",event=>{ const demo=event.target.closest("[data-demo]"); if(!demo)return; const slug=demo.dataset.demo; const state=states.get(slug); if(event.target.closest("[data-reset]")){states.set(slug,initial(slug));render(slug);return;} const place=event.target.closest("[data-place]");if(place){notify(`${place.dataset.place} selected`);return;} const layer=event.target.closest("[data-layer]");if(layer){patch(slug,{layer:layer.dataset.layer});return;} const tool=event.target.closest("[data-tool]");if(tool){patch(slug,{tool:tool.dataset.tool,notes:tool.dataset.tool==="note"?state.notes+1:state.notes});return;} const step=event.target.closest("[data-step]");if(step){patch(slug,{step:Number(step.dataset.step),playing:false});return;} const day=event.target.closest("[data-day]");if(day){patch(slug,{day:Number(day.dataset.day)});return;} const mode=event.target.closest("[data-mode]");if(mode){patch(slug,{mode:mode.dataset.mode});return;} const filter=event.target.closest("[data-filter]");if(filter){patch(slug,{filter:filter.dataset.filter});return;} const category=event.target.closest("[data-category]");if(category){patch(slug,{category:category.dataset.category});return;} const action=event.target.closest("[data-action]")?.dataset.action; if(action==="tilt"){patch(slug,{tilted:!state.tilted});return;}if(action==="landmarks"){notify("3D landmarks toggled");return;}if(action==="play"){patch(slug,{step:(state.step+1)%4,playing:true});return;}if(action==="sheet"){patch(slug,{open:!state.open});return;}if(action==="search"){notify("12 places refreshed in this area");return;}if(action==="next"){notify("Showing the next editorial place");}});
grid.addEventListener("input",event=>{const demo=event.target.closest("[data-demo]");if(!demo)return;const slug=demo.dataset.demo;if(event.target.matches("[data-time]"))patch(slug,{hour:Number(event.target.value)});if(event.target.matches("[data-replay]"))patch(slug,{step:Number(event.target.value),playing:false});if(event.target.matches("[data-compare]"))patch(slug,{split:Number(event.target.value)});});
