import { useMemo, useState } from "react";
import "./travel-filter-design-demos.css";

type PlaceKind = "Stay" | "Eat" | "Drink" | "See" | "Shop";
type Status = "Everything" | "Visited" | "Want to go";
type Grouping = "Region" | "Type";
const places: Array<{ name: string; area: string; kind: PlaceKind; count: number; color: string }> = [
  { name: "Casa Mosaico", area: "Alfama · Lisbon", kind: "Stay", count: 12, color: "coral" },
  { name: "Manteigaria", area: "Baixa · Lisbon", kind: "Eat", count: 8, color: "gold" },
  { name: "The Gin Room", area: "Mouraria · Lisbon", kind: "Drink", count: 5, color: "plum" },
  { name: "Miradouro da Graça", area: "Graça · Lisbon", kind: "See", count: 6, color: "green" },
];
const kinds: Array<PlaceKind | "All"> = ["All", "Stay", "Eat", "Drink", "See", "Shop"];

function ResultContext({ query, kind, variant = "cards" }: { query: string; kind: PlaceKind | "All"; variant?: "cards" | "map" | "timeline" }) {
  const filtered = useMemo(() => places.filter((p) => (kind === "All" || p.kind === kind) && (!query || `${p.name} ${p.area}`.toLowerCase().includes(query.toLowerCase()))), [kind, query]);
  return <div className={`tfd-results tfd-results-${variant}`}><div className="tfd-results-head"><strong>{filtered.length ? `${filtered.length * 7 + 3} places` : "No places"}</strong><span>Lisbon · 24 saved</span></div>{variant === "map" ? <div className="tfd-mini-map" aria-label="Simulated Lisbon map"><i /><i /><b>1</b><b>2</b><b>3</b><small>Alfama</small></div> : <div className="tfd-place-list">{filtered.slice(0, 3).map((p) => <div className="tfd-place" key={p.name}><i className={p.color} /><span><strong>{p.name}</strong><small>{p.area} · {p.kind}</small></span><em>{p.count}</em></div>)}</div>}</div>;
}

function Search({ query, setQuery, placeholder = "Search places" }: { query: string; setQuery: (v: string) => void; placeholder?: string }) {
  return <label className="tfd-search"><span aria-hidden="true">⌕</span><input type="search" aria-label={placeholder} value={query} onChange={(e) => setQuery(e.target.value)} placeholder={placeholder} /></label>;
}
function Chips({ kind, setKind, labels = kinds }: { kind: PlaceKind | "All"; setKind: (k: PlaceKind | "All") => void; labels?: Array<PlaceKind | "All"> }) {
  return <div className="tfd-chips" role="group" aria-label="Place category">{labels.map((k) => <button type="button" key={k} aria-pressed={kind === k} className={kind === k ? "is-selected" : ""} onClick={() => setKind(k)}>{k === "All" ? "All places" : k}<small>{k === "All" ? 24 : places.find((p) => p.kind === k)?.count ?? 0}</small></button>)}</div>;
}

function FilterContext({ state }: { state: State }) {
  const [showSearch, setShowSearch] = useState(false);
  return <div className="tfd-context" role="group" aria-label="Additional travel filters"><button type="button" className={showSearch ? "is-selected" : ""} aria-expanded={showSearch} onClick={() => setShowSearch(!showSearch)}>⌕ Search</button>{showSearch && <Search query={state.query} setQuery={state.setQuery} placeholder="Search places" />}<div className="tfd-context-segment" role="group" aria-label="Visit status">{(["Everything", "Visited", "Want to go"] as const).map((value) => <button type="button" key={value} aria-pressed={state.status === value} className={state.status === value ? "is-selected" : ""} onClick={() => state.setStatus(value)}>{value}</button>)}</div><div className="tfd-context-segment" role="group" aria-label="Group places">{(["Region", "Type"] as const).map((value) => <button type="button" key={value} aria-pressed={state.grouping === value} className={state.grouping === value ? "is-selected" : ""} onClick={() => state.setGrouping(value)}>By {value}</button>)}</div></div>;
}

function Frame({ number, title, rationale, children }: { number: number; title: string; rationale: string; children: React.ReactNode }) {
  return <article className={`tfd-option tfd-option-${number}`}><div className="tfd-copy"><span>{String(number).padStart(2, "0")}</span><div><h2>{title}{number === 3 ? <mark>Recommended</mark> : null}</h2><p>{rationale}</p></div></div><div className="tfd-browser"><div className="tfd-browser-bar"><i /><i /><i /><span>wanderfile.app/travel</span></div><div className="tfd-page">{children}</div></div></article>;
}

function Demo({ number, title, rationale, children }: { number: number; title: string; rationale: string; children: (state: State) => React.ReactNode }) {
  const [query, setQuery] = useState(""); const [kind, setKind] = useState<PlaceKind | "All">("All"); const [open, setOpen] = useState(false);
  const [status, setStatus] = useState<Status>("Everything"); const [grouping, setGrouping] = useState<Grouping>("Type");
  const state = { query, setQuery, kind, setKind, open, setOpen, status, setStatus, grouping, setGrouping };
  return <Frame number={number} title={title} rationale={rationale}><>{children(state)}<FilterContext state={state} /></></Frame>;
}
type State = { query: string; setQuery: (v: string) => void; kind: PlaceKind | "All"; setKind: (k: PlaceKind | "All") => void; open: boolean; setOpen: (v: boolean) => void; status: Status; setStatus: (v: Status) => void; grouping: Grouping; setGrouping: (v: Grouping) => void };

export function TravelFilterDesignDemos() {
  return <main className="tfd-page-root"><header className="tfd-intro"><a href="/travel">← Travel</a><p>Filter explorations · developer gallery</p><h1>Find your kind of place.</h1><span>Ten interactive directions for the Travel page. Each keeps search, status, grouping, and place types in view.</span><a className="tfd-crosslink" href="/dev/travel-view-toggle">Compare the map / covers gallery →</a></header><section className="tfd-grid">
    <Demo number={1} title="Search tokens" rationale="Turn every active choice into a removable, readable token.">{({ query, setQuery, kind, setKind }) => <><Search query={query} setQuery={setQuery} placeholder="Search Lisbon, Kyoto…" /><div className="tfd-token-row"><button type="button" onClick={() => setKind("All")}>Lisbon ×</button>{kind !== "All" && <button type="button" onClick={() => setKind("All")}>{kind} ×</button>}<button type="button" onClick={() => setKind("See")}>+ Filter</button></div><ResultContext query={query} kind={kind} /></>}</Demo>
    <Demo number={2} title="Editorial categories" rationale="A browsable icon shelf makes place types feel like destinations in their own right.">{({ kind, setKind }) => <><div className="tfd-icon-shelf">{(["All", "Stay", "Eat", "Drink", "See", "Shop"] as const).map((k, i) => <button type="button" key={k} aria-pressed={kind === k} className={kind === k ? "is-selected" : ""} onClick={() => setKind(k)}><span>{["✦", "⌂", "♨", "◒", "◉", "◇"][i]}</span>{k}</button>)}</div><ResultContext query="" kind={kind} /></>}</Demo>
    <Demo number={3} title="Quiet toolbar" rationale="Progressive disclosure keeps the everyday toolbar compact while advanced filters stay one tap away.">{({ query, setQuery, kind, setKind, open, setOpen }) => <><div className="tfd-quiet-toolbar"><Search query={query} setQuery={setQuery} /><button type="button" className={open ? "is-selected" : ""} aria-pressed={open} onClick={() => setOpen(!open)}>Filters <b>3</b>⌄</button></div>{open && <div className="tfd-disclosure"><Chips kind={kind} setKind={setKind} /><button type="button" onClick={() => setKind("All")}>Reset all</button></div>}<ResultContext query={query} kind={kind} /></>}</Demo>
    <Demo number={4} title="Faceted side rail" rationale="A persistent facet rail makes counts scannable and keeps results context visible.">{({ kind, setKind, query, setQuery }) => <div className="tfd-facet-layout"><aside><strong>Refine</strong><Search query={query} setQuery={setQuery} /><Chips kind={kind} setKind={setKind} labels={["All", "Stay", "Eat", "See"]} /><button type="button" onClick={() => setKind("All")}>Clear facets</button></aside><ResultContext query={query} kind={kind} /></div>}</Demo>
    <Demo number={5} title="Bottom-sheet tray" rationale="On small screens, a peekable tray keeps the map and filter relationship tangible.">{({ kind, setKind, open, setOpen }) => <><div className="tfd-map-large"><b>1</b><b>2</b><b>3</b><span>Lisbon · 24 places</span></div><button type="button" className="tfd-tray-toggle" aria-expanded={open} onClick={() => setOpen(!open)}>⌃ &nbsp; Filter places <strong>24</strong></button>{open && <div className="tfd-tray"><Chips kind={kind} setKind={setKind} /><button type="button" onClick={() => setOpen(false)}>Show {kind === "All" ? 24 : 7} places</button></div>}</>}</Demo>
    <Demo number={6} title="Command palette" rationale="A keyboard-friendly command surface makes complex filtering feel fast and intentional.">{({ query, setQuery, kind, setKind, open, setOpen }) => <><button type="button" className="tfd-command-trigger" onClick={() => setOpen(true)}>⌘ K <span>Filter your atlas…</span></button>{open && <div className="tfd-command"><Search query={query} setQuery={setQuery} placeholder="Type a filter…" />{kinds.slice(1).map((k) => <button type="button" key={k} aria-pressed={kind === k} className={kind === k ? "is-selected" : ""} onClick={() => { setKind(k); setOpen(false); }}>Add {k}<small>{k} places</small></button>)}<button type="button" onClick={() => setOpen(false)}>Close palette</button></div>}<ResultContext query={query} kind={kind} /></>}</Demo>
    <Demo number={7} title="Luggage tags" rationale="Physical-looking tags give saved places a warm, tactile filing-system personality.">{({ kind, setKind }) => <><div className="tfd-tags">{kinds.map((k) => <button type="button" key={k} aria-pressed={kind === k} className={`${kind === k ? "is-selected" : ""} tfd-tag`} onClick={() => setKind(k)}>{k === "All" ? "Everything" : k}<small>{k === "All" ? 24 : 7}</small></button>)}</div><ResultContext query="" kind={kind} /></>}</Demo>
    <Demo number={8} title="Itinerary rail" rationale="Filters become trip chapters, aligning the library with the way a day unfolds.">{({ kind, setKind }) => <><div className="tfd-timeline"><button type="button" onClick={() => setKind("All")} aria-pressed={kind === "All"}>01 <strong>Any day</strong><small>24 saved</small></button>{(["Stay", "Eat", "See"] as const).map((k, i) => <button type="button" key={k} onClick={() => setKind(k)} aria-pressed={kind === k} className={kind === k ? "is-selected" : ""}>{`0${i + 2}`} <strong>{k === "Stay" ? "Arrive" : k === "Eat" ? "Long lunch" : "Wander"}</strong><small>{k} · 7 places</small></button>)}</div><ResultContext query="" kind={kind} variant="timeline" /></>}</Demo>
    <Demo number={9} title="Map legend" rationale="A floating legend turns geographic browsing into a direct, low-friction filter." >{({ kind, setKind }) => <><div className="tfd-map-large"><b>1</b><b>2</b><b>3</b><span>Drag map · 24 places</span><div className="tfd-legend">{(["All", "Stay", "Eat", "See"] as const).map((k) => <button type="button" key={k} aria-pressed={kind === k} className={kind === k ? "is-selected" : ""} onClick={() => setKind(k)}><i />{k}</button>)}</div></div><ResultContext query="" kind={kind} variant="map" /></>}</Demo>
    <Demo number={10} title="Natural sentence" rationale="A human sentence makes the current query legible: places are filtered in plain language.">{({ kind, setKind }) => <><div className="tfd-sentence">Show me <button type="button" onClick={() => setKind(kind === "See" ? "All" : "See")} aria-pressed={kind === "See"}>{kind === "See" ? "views" : "all places"}</button> to <button type="button" onClick={() => setKind("Eat")} aria-pressed={kind === "Eat"}>eat</button> <span>in Lisbon</span>.</div><div className="tfd-sentence-status">{kind === "All" ? "Everything" : kind} · Any status · Any region <button type="button" onClick={() => setKind("All")}>Clear</button></div><ResultContext query="" kind={kind} /></>}</Demo>
  </section></main>;
}
