/**
 * Shared mock content for Wanderfile complete-site prototypes.
 *
 * Attached to window.WF_MOCK for every page in every site (via <script>).
 * Photos are stable Unsplash CDN URLs (proven-permanent photo IDs).
 * Every place has a hero + gallery; every post has a poster image so grids
 * feel real and colorful, matching the reference designs.
 */
(function () {
  const UNSPLASH = (id, w = 1200, h = 800) =>
    `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&auto=format&q=75`;

  // Curated pool of known-good travel photos from Unsplash's editorial CDN.
  const PHOTO = {
    kyotoTemple: "photo-1528360983277-13d401cdc186",
    kyotoStreet: "photo-1493976040374-85c8e12f0c0e",
    kyotoBamboo: "photo-1528164344705-47542687000d",
    lisbonYellow: "photo-1580323956656-26bbb1206e34",
    lisbonAlfama: "photo-1585208798174-6cedd86e019a",
    lisbonTram: "photo-1548013146-72479768bada",
    patagoniaPeaks: "photo-1520962880247-cfaf541c8724",
    patagoniaLake: "photo-1483347756197-71ef80e95f73",
    patagoniaHiker: "photo-1454391304352-2bf4678b1a7a",
    mexicoCitySkyline: "photo-1512813195386-6cf811ad3542",
    mexicoCityCathedral: "photo-1531253450048-6db83d452fdb",
    mexicoCityStreet: "photo-1518659526054-190340b32735",
    amalfiPositano: "photo-1533106497176-45ae19e68ba2",
    amalfiCoast: "photo-1548574505-5e239809ee19",
    amalfiCliffs: "photo-1523906834658-6e24ef2386f9",
    reykjavik: "photo-1490650034439-fd184c3c86a5",
    icelandWaterfall: "photo-1476514525535-07fb3b4ae5f1",
    icelandBlack: "photo-1531168556467-80aace0d0144",
    kinosakiOnsen: "photo-1526481280695-3c469368e8b4",
    cappadociaBalloons: "photo-1523592121529-f6dde35f079e",
    cappadociaSunrise: "photo-1520939817895-060bdaf4fe1b",
    cappadociaCaves: "photo-1587310466442-0a0c0c85fbc3",
    baliRice: "photo-1537996194471-e657df975ab4",
    baliTemple: "photo-1512100356356-de1b84283e18",
    peruMachu: "photo-1526392060635-9d6019884377",
    peruCusco: "photo-1531065208531-4036c0dba3ca",
    marrakechSouk: "photo-1489749798305-4fea3ae63d43",
    marrakechRiad: "photo-1548013146-72479768bada",
    santoriniBlue: "photo-1533105079780-92b9be482077",
    santoriniSunset: "photo-1613395877344-13d4a8e0d49e",
    swissMountains: "photo-1527668752968-14dc70a27c95",
    swissLake: "photo-1527668752968-14dc70a27c95",
    norwayFjord: "photo-1506905925346-21bda4d32df4",
    baliBeach: "photo-1537996194471-e657df975ab4",
    thailandBeach: "photo-1552465011-b4e21bf6e79a",
    parisEiffel: "photo-1502602898657-3e91760cbb34",
    parisCafe: "photo-1499856871958-5b9627545d1a",
    newYorkSkyline: "photo-1496442226666-8d4d0e62e6e9",
    tokyoNeon: "photo-1540959733332-eab4deabeeaf",
    tokyoStreet: "photo-1503899036084-c55cdd92da26",
    dubaiSkyline: "photo-1518684079-3c830dcef090",
    hikerSummit: "photo-1519681393784-d120267933ba",
    campingTent: "photo-1504280390367-361c6d9f38f4",
    cyclingRoad: "photo-1441974231531-c6227db76b6e",
    photographer: "photo-1502920917128-1aa500764cbd",
    portraitMan: "photo-1500648767791-00dcc994a43e",
    portraitWoman: "photo-1494790108377-be9c29b29330",
    portraitGuide: "photo-1507003211169-0a1dd7228f2d",
    portraitTraveler1: "photo-1544005313-94ddf0286df2",
    portraitTraveler2: "photo-1521119989659-a83eee488004",
    portraitTraveler3: "photo-1531123897727-8f129e1688ce",
    balloonSky: "photo-1503656142023-618e7d1f435a",
    desertDunes: "photo-1509316785289-025f5b846b35",
    forestPath: "photo-1441974231531-c6227db76b6e",
    northernLights: "photo-1483347756197-71ef80e95f73",
    tropicalIsland: "photo-1439066615861-d1af74d74000",
    riverRafting: "photo-1502581827181-9cf3c3ee0106",
    streetFood: "photo-1504674900247-0877df9cc836",
    coffeeShop: "photo-1521017432531-fbd92d768814",
    architecture: "photo-1470071459604-3b5ec3a7fe05",
    ancientRuins: "photo-1548013146-72479768bada",
    coastalRoad: "photo-1502920917128-1aa500764cbd",
  };

  const img = (key, w, h) => UNSPLASH(PHOTO[key], w, h);

  const PLACES = [
    {
      id: "kyoto",
      name: "Kyoto",
      region: "Kansai",
      country: "Japan",
      continent: "Asia",
      lat: 35.0116,
      lng: 135.7681,
      category: "landmark",
      visited: true,
      postCount: 12,
      tagline: "Temples, tea houses, and lanterns you'll photograph twice.",
      summary:
        "A thousand years of imperial capital layered under bamboo groves and matcha counters. Base yourself near Gion, wake up early for the shrines, and stay out for the machiya alleys after dark.",
      hero: img("kyotoTemple", 1800, 1000),
      gallery: [
        img("kyotoTemple", 900, 700),
        img("kyotoStreet", 900, 700),
        img("kyotoBamboo", 900, 700),
      ],
      accent: "#c9805a",
      bestSeason: "March – May, October",
      tags: ["culture", "food", "walkable"],
    },
    {
      id: "lisbon",
      name: "Lisbon",
      region: "Estremadura",
      country: "Portugal",
      continent: "Europe",
      lat: 38.7223,
      lng: -9.1393,
      category: "city",
      visited: true,
      postCount: 9,
      tagline: "Pastel walks, tiled facades, and a river that catches the sun.",
      summary:
        "Seven hills, three-drink lunches, and a light that photographers refuse to shut up about. Ride the 28, eat pastéis in Belém, take the ferry to Cacilhas at sunset.",
      hero: img("lisbonYellow", 1800, 1000),
      gallery: [
        img("lisbonYellow", 900, 700),
        img("lisbonAlfama", 900, 700),
        img("lisbonTram", 900, 700),
      ],
      accent: "#e8a24a",
      bestSeason: "April – June, September",
      tags: ["city", "food", "walkable"],
    },
    {
      id: "torres-del-paine",
      name: "Torres del Paine",
      region: "Patagonia",
      country: "Chile",
      continent: "Americas",
      lat: -50.9423,
      lng: -73.4068,
      category: "hike",
      visited: false,
      postCount: 4,
      tagline: "Granite spires, glacier lakes, and wind that means it.",
      summary:
        "The W trek, the O trek, or a base at Ecocamp — pick your commitment. Weather turns fast; pack for four seasons in a single afternoon.",
      hero: img("patagoniaPeaks", 1800, 1000),
      gallery: [
        img("patagoniaPeaks", 900, 700),
        img("patagoniaLake", 900, 700),
        img("patagoniaHiker", 900, 700),
      ],
      accent: "#4d7ea3",
      bestSeason: "November – March",
      tags: ["outdoors", "hiking", "epic"],
    },
    {
      id: "mexico-city",
      name: "Mexico City",
      region: "CDMX",
      country: "Mexico",
      continent: "Americas",
      lat: 19.4326,
      lng: -99.1332,
      category: "city",
      visited: false,
      postCount: 11,
      tagline: "Late-night tacos, murals, and colonial plazas that never quiet down.",
      summary:
        "Roma Norte for coffee, Coyoacán for markets, Xochimilco for the boats. Every meal is a decision.",
      hero: img("mexicoCitySkyline", 1800, 1000),
      gallery: [
        img("mexicoCitySkyline", 900, 700),
        img("mexicoCityCathedral", 900, 700),
        img("mexicoCityStreet", 900, 700),
      ],
      accent: "#d4523e",
      bestSeason: "March – May",
      tags: ["city", "food", "art"],
    },
    {
      id: "positano",
      name: "Positano",
      region: "Amalfi Coast",
      country: "Italy",
      continent: "Europe",
      lat: 40.628,
      lng: 14.4849,
      category: "hotel",
      visited: true,
      postCount: 6,
      tagline: "Cliffs, ferries, and a sunset that refuses to end.",
      summary:
        "Stay one night up in Praiano to skip the crowds, take the boat to Capri, and don't miss the granita at Collina Bakery.",
      hero: img("amalfiPositano", 1800, 1000),
      gallery: [
        img("amalfiPositano", 900, 700),
        img("amalfiCoast", 900, 700),
        img("amalfiCliffs", 900, 700),
      ],
      accent: "#e07e5f",
      bestSeason: "May, September – October",
      tags: ["coast", "romantic", "photogenic"],
    },
    {
      id: "reykjavik",
      name: "Reykjavík",
      region: "Capital",
      country: "Iceland",
      continent: "Europe",
      lat: 64.1466,
      lng: -21.9426,
      category: "city",
      visited: false,
      postCount: 5,
      tagline: "Geothermal pools, black sand, and a waterfall worth the detour.",
      summary:
        "Base for the south coast day trip: Seljalandsfoss → Skógafoss → Reynisfjara → Vík. Rent a small car; the Ring Road can wait.",
      hero: img("reykjavik", 1800, 1000),
      gallery: [
        img("reykjavik", 900, 700),
        img("icelandWaterfall", 900, 700),
        img("icelandBlack", 900, 700),
      ],
      accent: "#4a7a8c",
      bestSeason: "June – August, February",
      tags: ["nordic", "outdoors", "photography"],
    },
    {
      id: "kinosaki",
      name: "Kinosaki Onsen",
      region: "Hyōgo",
      country: "Japan",
      continent: "Asia",
      lat: 35.6235,
      lng: 134.8056,
      category: "cafe",
      visited: false,
      postCount: 3,
      tagline: "A whole town in yukatas, seven baths, one long exhale.",
      summary:
        "Show up by train, put on the robe, don't take it off. Winter for snow-crab kaiseki; spring for cherry trees along the canal.",
      hero: img("kinosakiOnsen", 1800, 1000),
      gallery: [img("kinosakiOnsen", 900, 700), img("kyotoBamboo", 900, 700)],
      accent: "#7fa382",
      bestSeason: "November – March",
      tags: ["wellness", "quiet", "food"],
    },
    {
      id: "cappadocia",
      name: "Cappadocia",
      region: "Central Anatolia",
      country: "Turkey",
      continent: "Asia",
      lat: 38.6431,
      lng: 34.8289,
      category: "viewpoint",
      visited: false,
      postCount: 8,
      tagline: "Balloons at dawn, cave hotels at night, valleys in between.",
      summary:
        "Stay in Göreme, book the balloon flight for your second morning (in case day one is cancelled), and hike the Rose Valley on foot.",
      hero: img("cappadociaBalloons", 1800, 1000),
      gallery: [
        img("cappadociaBalloons", 900, 700),
        img("cappadociaSunrise", 900, 700),
        img("cappadociaCaves", 900, 700),
      ],
      accent: "#d97a45",
      bestSeason: "April – June, September – October",
      tags: ["outdoors", "epic", "sunrise"],
    },
    {
      id: "bali",
      name: "Ubud",
      region: "Bali",
      country: "Indonesia",
      continent: "Asia",
      lat: -8.5069,
      lng: 115.2625,
      category: "restaurant",
      visited: false,
      postCount: 7,
      tagline: "Rice terraces, temple mornings, and a smoothie bowl on every corner.",
      summary:
        "Rent a scooter, wake up for Tegallalang before the buses, and always leave a night for a cliffside seafood dinner in Jimbaran.",
      hero: img("baliRice", 1800, 1000),
      gallery: [img("baliRice", 900, 700), img("baliTemple", 900, 700)],
      accent: "#7fa670",
      bestSeason: "April – October",
      tags: ["wellness", "tropical", "yoga"],
    },
    {
      id: "cusco",
      name: "Cusco & Machu Picchu",
      region: "Sacred Valley",
      country: "Peru",
      continent: "Americas",
      lat: -13.5319,
      lng: -71.9675,
      category: "culture",
      visited: false,
      postCount: 6,
      tagline: "Inca stonework, altitude, and one very worth-it early train.",
      summary:
        "Give yourself two days in Cusco to acclimatize. Book Machu Picchu tickets weeks ahead; go for the sunrise entrance if you can.",
      hero: img("peruMachu", 1800, 1000),
      gallery: [img("peruMachu", 900, 700), img("peruCusco", 900, 700)],
      accent: "#a5734f",
      bestSeason: "May – September",
      tags: ["culture", "hiking", "epic"],
    },
    {
      id: "marrakech",
      name: "Marrakech",
      region: "Marrakech-Safi",
      country: "Morocco",
      continent: "Africa",
      lat: 31.6295,
      lng: -7.9811,
      category: "market",
      visited: false,
      postCount: 5,
      tagline: "Souks, riads, and mint tea served three times.",
      summary:
        "Sleep inside the medina at a small riad. Get lost on purpose. Come back to the Jardin Majorelle for a quiet afternoon.",
      hero: img("marrakechSouk", 1800, 1000),
      gallery: [img("marrakechSouk", 900, 700), img("marrakechRiad", 900, 700)],
      accent: "#c65b3e",
      bestSeason: "March – May, September – November",
      tags: ["culture", "food", "market"],
    },
    {
      id: "santorini",
      name: "Santorini",
      region: "Cyclades",
      country: "Greece",
      continent: "Europe",
      lat: 36.3932,
      lng: 25.4615,
      category: "beach",
      visited: true,
      postCount: 7,
      tagline: "White cliffs, blue domes, and caldera sunsets that earn the cliché.",
      summary:
        "Skip Oia at sunset (or accept the crowd), and stay in Imerovigli for the view without the shove.",
      hero: img("santoriniBlue", 1800, 1000),
      gallery: [img("santoriniBlue", 900, 700), img("santoriniSunset", 900, 700)],
      accent: "#4a90c4",
      bestSeason: "May, June, September",
      tags: ["coast", "romantic", "sunset"],
    },
  ];

  const POSTS = [
    {
      id: "ig-001",
      platform: "instagram",
      author: "@ryosukejapan",
      title: "Hidden onsen towns outside Kyoto",
      excerpt:
        "Three villages, one day trip, zero crowds. Steam, cedar, and quiet mornings.",
      places: ["kinosaki", "kyoto"],
      tags: ["onsen", "japan", "day-trip"],
      posted: "Mar 12",
      duration: "0:48",
      cover: img("kinosakiOnsen", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "web-001",
      platform: "web",
      author: "Lisbon Diary",
      title: "Lisbon's best pastel walks",
      excerpt: "A pastry-forward route through Alfama, Baixa, and the riverfront.",
      places: ["lisbon"],
      tags: ["food", "walking", "portugal"],
      posted: "Feb 28",
      readTime: "6 min",
      cover: img("lisbonYellow", 900, 700),
      aspect: 1.35,
    },
    {
      id: "yt-001",
      platform: "youtube",
      author: "Kara Explores",
      title: "Patagonia without the rush",
      excerpt: "Base camps, slow trails, and lakes that look unreal at golden hour.",
      places: ["torres-del-paine"],
      tags: ["hiking", "nature", "chile"],
      posted: "Jan 4",
      duration: "14:22",
      cover: img("patagoniaPeaks", 900, 550),
      aspect: 1.7,
    },
    {
      id: "yt-002",
      platform: "youtube",
      author: "Off Menu",
      title: "48 hours in Mexico City",
      excerpt: "Markets, museums, and late-night tacos — a tight loop for first-timers.",
      places: ["mexico-city"],
      tags: ["city", "food", "cdmx"],
      posted: "Dec 18",
      duration: "18:07",
      cover: img("mexicoCityStreet", 900, 550),
      aspect: 1.7,
    },
    {
      id: "ig-002",
      platform: "instagram",
      author: "@amalfilocal",
      title: "Amalfi cliffs at blue hour",
      excerpt: "Ferry hops, lemon groves, and a sunset that refuses to end.",
      places: ["positano"],
      tags: ["coast", "sunset", "italy"],
      posted: "Nov 2",
      duration: "0:35",
      cover: img("amalfiPositano", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "web-002",
      platform: "web",
      author: "Nordic Notes",
      title: "Reykjavík day trips that matter",
      excerpt: "Geothermal pools, black sand, and one waterfall worth the detour.",
      places: ["reykjavik"],
      tags: ["nordic", "day-trip", "iceland"],
      posted: "Oct 9",
      readTime: "8 min",
      cover: img("icelandWaterfall", 900, 700),
      aspect: 1.35,
    },
    {
      id: "tk-001",
      platform: "tiktok",
      author: "@balloonwake",
      title: "5:20 AM in Cappadocia",
      excerpt: "The wake-up is worth it. Watch until the whole sky lifts.",
      places: ["cappadocia"],
      tags: ["sunrise", "epic", "turkey"],
      posted: "Sep 21",
      duration: "0:41",
      cover: img("cappadociaBalloons", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "ig-003",
      platform: "instagram",
      author: "@ubudmornings",
      title: "One week in Ubud — the honest version",
      excerpt: "Yoga, rice fields, and how to skip the scooter chaos.",
      places: ["bali"],
      tags: ["wellness", "bali", "yoga"],
      posted: "Sep 5",
      duration: "1:12",
      cover: img("baliRice", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "yt-003",
      platform: "youtube",
      author: "Trail Cinema",
      title: "Machu Picchu at sunrise, on foot",
      excerpt: "Four days on the Salkantay — quiet mornings, dramatic ridges.",
      places: ["cusco"],
      tags: ["hiking", "peru", "sunrise"],
      posted: "Aug 12",
      duration: "22:04",
      cover: img("peruMachu", 900, 550),
      aspect: 1.7,
    },
    {
      id: "web-003",
      platform: "web",
      author: "Riad Report",
      title: "A slow week in Marrakech",
      excerpt: "Souks in the morning, riad in the afternoon, rooftop at dusk.",
      places: ["marrakech"],
      tags: ["culture", "morocco", "slow"],
      posted: "Jul 30",
      readTime: "10 min",
      cover: img("marrakechSouk", 900, 700),
      aspect: 1.35,
    },
    {
      id: "ig-004",
      platform: "instagram",
      author: "@bluedome",
      title: "Skip Oia. Try Imerovigli.",
      excerpt: "Same sunset, half the elbows. Two spots that will change your evening.",
      places: ["santorini"],
      tags: ["sunset", "greece", "tip"],
      posted: "Jul 8",
      duration: "0:22",
      cover: img("santoriniBlue", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "tk-002",
      platform: "tiktok",
      author: "@onsenoclock",
      title: "How to do Kinosaki in one night",
      excerpt: "Yukata, seven baths, one snow crab dinner. Go.",
      places: ["kinosaki"],
      tags: ["onsen", "japan", "wellness"],
      posted: "Jun 14",
      duration: "0:57",
      cover: img("kyotoBamboo", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "yt-004",
      platform: "youtube",
      author: "Kara Explores",
      title: "The Cusco altitude playbook",
      excerpt: "How to acclimatize in 48 hours without killing your first hike.",
      places: ["cusco"],
      tags: ["hiking", "peru", "tips"],
      posted: "Jun 2",
      duration: "9:41",
      cover: img("peruCusco", 900, 550),
      aspect: 1.7,
    },
    {
      id: "ig-005",
      platform: "instagram",
      author: "@lisbontram",
      title: "Alfama at 7am, no one else awake",
      excerpt: "The quiet version of the city. Better light, better coffee, no line.",
      places: ["lisbon"],
      tags: ["walking", "portugal", "morning"],
      posted: "May 20",
      duration: "0:30",
      cover: img("lisbonAlfama", 900, 1200),
      aspect: 0.72,
    },
    {
      id: "web-004",
      platform: "web",
      author: "Cliff Notes",
      title: "How to actually book Positano",
      excerpt: "The hotel math, the ferry schedule, and where to sleep instead.",
      places: ["positano"],
      tags: ["planning", "italy", "coast"],
      posted: "May 3",
      readTime: "12 min",
      cover: img("amalfiCliffs", 900, 700),
      aspect: 1.35,
    },
    {
      id: "ig-006",
      platform: "instagram",
      author: "@thunderbelow",
      title: "Torres del Paine — day 3",
      excerpt: "Wind so loud you can't hear yourself. The view: worth it.",
      places: ["torres-del-paine"],
      tags: ["hiking", "chile", "epic"],
      posted: "Apr 18",
      duration: "0:39",
      cover: img("patagoniaHiker", 900, 1200),
      aspect: 0.72,
    },
  ];

  const VISITS = [
    { id: "v1", placeId: "kyoto", when: "April 2024", note: "Cherry week — stayed near Gion. Woke up for Fushimi Inari before sunrise.", rating: 5 },
    { id: "v2", placeId: "lisbon", when: "September 2023", note: "Tram 28, pastéis every morning. Two nights was not enough.", rating: 4 },
    { id: "v3", placeId: "positano", when: "July 2022", note: "One night, worth every euro. Book Praiano next time.", rating: 5 },
    { id: "v4", placeId: "santorini", when: "May 2022", note: "Imerovigli tip held up. Sunset without the shove.", rating: 4 },
    { id: "v5", placeId: "kyoto", when: "November 2019", note: "Fall colors at Eikan-dō. Bring a real jacket.", rating: 5 },
  ];

  const TESTIMONIALS = [
    {
      name: "Cody Palmer",
      role: "Photographer, Brooklyn",
      quote:
        "I stopped losing reels to my saved folder. Wanderfile just knows what I meant to bookmark.",
      avatar: img("portraitMan", 200, 200),
      rating: 5,
    },
    {
      name: "Marta Novak",
      role: "Product designer, Lisbon",
      quote:
        "My trip planning went from 12 tabs to a single atlas. I know which places I've saved and which I've actually walked.",
      avatar: img("portraitWoman", 200, 200),
      rating: 5,
    },
    {
      name: "Aditi Rao",
      role: "Travel writer, Mumbai",
      quote:
        "The share sheet to Wanderfile is the fastest step of my whole workflow. Everything else builds itself.",
      avatar: img("portraitGuide", 200, 200),
      rating: 5,
    },
  ];

  const CATEGORIES = [
    { key: "outdoors", label: "Outdoors", icon: "🏔️", cover: img("hikerSummit", 900, 700) },
    { key: "coast", label: "Coast & islands", icon: "🌊", cover: img("thailandBeach", 900, 700) },
    { key: "city", label: "City breaks", icon: "🏙️", cover: img("newYorkSkyline", 900, 700) },
    { key: "wellness", label: "Wellness & retreats", icon: "🧘", cover: img("baliRice", 900, 700) },
    { key: "culture", label: "Culture & history", icon: "🏛️", cover: img("marrakechSouk", 900, 700) },
    { key: "food", label: "Food-first", icon: "🍜", cover: img("streetFood", 900, 700) },
  ];

  const STATS = {
    posts: POSTS.length,
    places: PLACES.length,
    visits: VISITS.length,
    countries: new Set(PLACES.map((p) => p.country)).size,
  };

  window.WF_MOCK = {
    brand: "Wanderfile",
    tagline: "Turn scattered links into a curated travel atlas.",
    photos: PHOTO,
    img,
    places: PLACES,
    posts: POSTS,
    visits: VISITS,
    testimonials: TESTIMONIALS,
    categories: CATEGORIES,
    stats: STATS,
    placeById: (id) => PLACES.find((p) => p.id === id),
    postById: (id) => POSTS.find((p) => p.id === id),
    placesByIds: (ids) => ids.map((id) => PLACES.find((p) => p.id === id)).filter(Boolean),
    postsForPlace: (placeId) => POSTS.filter((p) => p.places.includes(placeId)),
    visitsForPlace: (placeId) => VISITS.filter((v) => v.placeId === placeId),
  };
})();
