/** Fallback post library for demos when the API has few/no posts. */

export interface DemoPost {
  post_id: string;
  post_url: string;
  platform: string;
  caption: string;
  hashtags: string[];
  author_handle: string;
  posted_at: string;
  place_names: string[];
  place_ids: string[];
  thumbnail_url: string | null;
  media_kind: string;
}

const thumbs = (seed: string, w = 640, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const DEMO_POSTS: DemoPost[] = [
  {
    post_id: "instagram:kyoto-onsen",
    post_url: "https://www.instagram.com/reel/demo1/",
    platform: "instagram",
    caption: "Hidden onsen towns outside Kyoto\nThree villages, one day trip, zero crowds.",
    hashtags: ["onsen", "japan", "daytrip"],
    author_handle: "slow.japan",
    posted_at: "2026-03-12T10:00:00Z",
    place_names: ["Kinosaki Onsen", "Kyoto"],
    place_ids: ["p-kinosaki", "p-kyoto"],
    thumbnail_url: thumbs("kyoto-onsen", 720, 900),
    media_kind: "reel",
  },
  {
    post_id: "web:lisbon-pastel",
    post_url: "https://example.com/lisbon-pastel-walks",
    platform: "web",
    caption: "Lisbon's best pastel walks\nA pastry-forward route through Alfama and Baixa.",
    hashtags: ["food", "walking"],
    author_handle: "citybites",
    posted_at: "2026-02-28T14:00:00Z",
    place_names: ["Alfama", "Lisbon"],
    place_ids: ["p-alfama", "p-lisbon"],
    thumbnail_url: thumbs("lisbon-pastel", 800, 600),
    media_kind: "article",
  },
  {
    post_id: "instagram:patagonia",
    post_url: "https://www.instagram.com/reel/demo3/",
    platform: "instagram",
    caption: "Patagonia without the rush\nBase camps, slow trails, unreal golden hour lakes.",
    hashtags: ["hiking", "nature"],
    author_handle: "ridge.line",
    posted_at: "2026-01-04T09:00:00Z",
    place_names: ["Torres del Paine", "Patagonia"],
    place_ids: ["p-tdp", "p-patagonia"],
    thumbnail_url: thumbs("patagonia", 700, 950),
    media_kind: "reel",
  },
  {
    post_id: "youtube:cdmx48",
    post_url: "https://www.youtube.com/watch?v=demo4",
    platform: "youtube",
    caption: "48 hours in Mexico City\nMarkets, museums, and late-night tacos.",
    hashtags: ["city", "food"],
    author_handle: "firsttimer",
    posted_at: "2025-12-18T18:00:00Z",
    place_names: ["Coyoacán", "Mexico City"],
    place_ids: ["p-coyo", "p-cdmx"],
    thumbnail_url: thumbs("cdmx48", 1280, 720),
    media_kind: "video",
  },
  {
    post_id: "instagram:amalfi",
    post_url: "https://www.instagram.com/reel/demo5/",
    platform: "instagram",
    caption: "Amalfi cliffs at blue hour\nFerry hops, lemon groves, a sunset that refuses to end.",
    hashtags: ["coast", "sunset"],
    author_handle: "blue.hour",
    posted_at: "2025-11-02T19:30:00Z",
    place_names: ["Positano", "Amalfi Coast"],
    place_ids: ["p-positano", "p-amalfi"],
    thumbnail_url: thumbs("amalfi", 720, 960),
    media_kind: "reel",
  },
  {
    post_id: "web:reykjavik",
    post_url: "https://example.com/reykjavik-day-trips",
    platform: "web",
    caption: "Reykjavík day trips that matter\nGeothermal pools, black sand, one waterfall detour.",
    hashtags: ["nordic", "daytrip"],
    author_handle: "north.notes",
    posted_at: "2025-10-09T11:00:00Z",
    place_names: ["Reykjavík", "Iceland"],
    place_ids: ["p-reyk", "p-iceland"],
    thumbnail_url: thumbs("reykjavik", 900, 700),
    media_kind: "article",
  },
  {
    post_id: "tiktok:tokyo-night",
    post_url: "https://www.tiktok.com/@demo/video/7",
    platform: "tiktok",
    caption: "Shinjuku after midnight\nNeon alleys, ramen steam, last train anxiety.",
    hashtags: ["tokyo", "night"],
    author_handle: "neon.walk",
    posted_at: "2026-03-01T22:00:00Z",
    place_names: ["Shinjuku", "Tokyo"],
    place_ids: ["p-shinjuku", "p-tokyo"],
    thumbnail_url: thumbs("tokyo-night", 720, 1280),
    media_kind: "video",
  },
  {
    post_id: "instagram:marrakech",
    post_url: "https://www.instagram.com/reel/demo8/",
    platform: "instagram",
    caption: "Marrakech medina in one morning\nRiads, spice lanes, and a quiet rooftop.",
    hashtags: ["morocco", "markets"],
    author_handle: "desert.door",
    posted_at: "2026-02-14T08:00:00Z",
    place_names: ["Marrakech"],
    place_ids: ["p-marrakech"],
    thumbnail_url: thumbs("marrakech", 800, 1000),
    media_kind: "reel",
  },
  {
    post_id: "youtube:bali-rice",
    post_url: "https://www.youtube.com/watch?v=demo9",
    platform: "youtube",
    caption: "Ubud rice terraces without the tour bus\nDawn light, quiet paths, coffee after.",
    hashtags: ["bali", "nature"],
    author_handle: "island.pace",
    posted_at: "2025-09-21T06:00:00Z",
    place_names: ["Tegallalang", "Ubud"],
    place_ids: ["p-tegal", "p-ubud"],
    thumbnail_url: thumbs("bali-rice", 1280, 720),
    media_kind: "video",
  },
  {
    post_id: "instagram:nyc-rooftop",
    post_url: "https://www.instagram.com/reel/demo10/",
    platform: "instagram",
    caption: "Brooklyn rooftops in October\nCrisp air, skyline, and one perfect sandwich.",
    hashtags: ["nyc", "autumn"],
    author_handle: "borough.bits",
    posted_at: "2025-10-22T16:00:00Z",
    place_names: ["Brooklyn", "New York"],
    place_ids: ["p-brooklyn", "p-nyc"],
    thumbnail_url: thumbs("nyc-roof", 720, 900),
    media_kind: "reel",
  },
  {
    post_id: "web:porto-tiles",
    post_url: "https://example.com/porto-tile-walk",
    platform: "web",
    caption: "Porto azulejo trail\nBlue tiles, river light, and a slow tram loop.",
    hashtags: ["portugal", "walking"],
    author_handle: "tile.trail",
    posted_at: "2026-01-19T12:00:00Z",
    place_names: ["Porto", "Ribeira"],
    place_ids: ["p-porto", "p-ribeira"],
    thumbnail_url: thumbs("porto-tiles", 850, 650),
    media_kind: "article",
  },
  {
    post_id: "tiktok:seoul-cafe",
    post_url: "https://www.tiktok.com/@demo/video/12",
    platform: "tiktok",
    caption: "Seongsu cafe crawl\nIndustrial chic, good light, better coffee.",
    hashtags: ["seoul", "cafes"],
    author_handle: "han.river",
    posted_at: "2026-02-02T15:00:00Z",
    place_names: ["Seongsu", "Seoul"],
    place_ids: ["p-seongsu", "p-seoul"],
    thumbnail_url: thumbs("seoul-cafe", 720, 1280),
    media_kind: "video",
  },
  {
    post_id: "instagram:cape-town",
    post_url: "https://www.instagram.com/reel/demo13/",
    platform: "instagram",
    caption: "Table Mountain before the cable car queue\nHike early, picnic on the plateau.",
    hashtags: ["hiking", "capetown"],
    author_handle: "fynbos.fog",
    posted_at: "2025-11-28T07:00:00Z",
    place_names: ["Table Mountain", "Cape Town"],
    place_ids: ["p-table", "p-cpt"],
    thumbnail_url: thumbs("cape-town", 760, 980),
    media_kind: "reel",
  },
  {
    post_id: "youtube:vienna-cafe",
    post_url: "https://www.youtube.com/watch?v=demo14",
    platform: "youtube",
    caption: "Vienna coffeehouse etiquette\nNewspapers, melange, and lingering without guilt.",
    hashtags: ["vienna", "cafes"],
    author_handle: "mittel.eu",
    posted_at: "2025-08-14T10:00:00Z",
    place_names: ["Vienna"],
    place_ids: ["p-vienna"],
    thumbnail_url: thumbs("vienna-cafe", 1280, 720),
    media_kind: "video",
  },
  {
    post_id: "instagram:banff",
    post_url: "https://www.instagram.com/reel/demo15/",
    platform: "instagram",
    caption: "Banff lake loop in shoulder season\nFewer crowds, colder water, better light.",
    hashtags: ["canada", "lakes"],
    author_handle: "rockies.slow",
    posted_at: "2025-09-03T13:00:00Z",
    place_names: ["Lake Louise", "Banff"],
    place_ids: ["p-louise", "p-banff"],
    thumbnail_url: thumbs("banff", 700, 920),
    media_kind: "reel",
  },
  {
    post_id: "web:hanoi-street",
    post_url: "https://example.com/hanoi-street-food",
    platform: "web",
    caption: "Hanoi street food map\nBun cha, egg coffee, and one alley you will miss.",
    hashtags: ["vietnam", "food"],
    author_handle: "pho.notes",
    posted_at: "2026-03-05T09:00:00Z",
    place_names: ["Hanoi", "Old Quarter"],
    place_ids: ["p-hanoi", "p-oldq"],
    thumbnail_url: thumbs("hanoi", 900, 700),
    media_kind: "article",
  },
  {
    post_id: "tiktok:santorini",
    post_url: "https://www.tiktok.com/@demo/video/17",
    platform: "tiktok",
    caption: "Oia without the sunset crush\nMorning caldera, blue domes, quiet stairs.",
    hashtags: ["greece", "islands"],
    author_handle: "aegean.light",
    posted_at: "2025-07-19T05:30:00Z",
    place_names: ["Oia", "Santorini"],
    place_ids: ["p-oia", "p-santorini"],
    thumbnail_url: thumbs("santorini", 720, 1280),
    media_kind: "video",
  },
  {
    post_id: "instagram:quebec",
    post_url: "https://www.instagram.com/reel/demo18/",
    platform: "instagram",
    caption: "Québec City in snow\nStone walls, warm cafés, soft footsteps.",
    hashtags: ["winter", "canada"],
    author_handle: "nord.ville",
    posted_at: "2026-01-11T17:00:00Z",
    place_names: ["Québec City"],
    place_ids: ["p-quebec"],
    thumbnail_url: thumbs("quebec", 720, 900),
    media_kind: "reel",
  },
  {
    post_id: "youtube:singapore",
    post_url: "https://www.youtube.com/watch?v=demo19",
    platform: "youtube",
    caption: "Singapore hawker essentials\nMaxwell, Lau Pa Sat, and one chili crab night.",
    hashtags: ["singapore", "food"],
    author_handle: "hawker.hour",
    posted_at: "2025-12-02T12:00:00Z",
    place_names: ["Singapore"],
    place_ids: ["p-sg"],
    thumbnail_url: thumbs("singapore", 1280, 720),
    media_kind: "video",
  },
  {
    post_id: "instagram:cusco",
    post_url: "https://www.instagram.com/reel/demo20/",
    platform: "instagram",
    caption: "Cusco acclimatization day\nSlow streets, coca tea, Sacred Valley preview.",
    hashtags: ["peru", "andes"],
    author_handle: "altitude.soft",
    posted_at: "2025-06-08T11:00:00Z",
    place_names: ["Cusco", "Sacred Valley"],
    place_ids: ["p-cusco", "p-valley"],
    thumbnail_url: thumbs("cusco", 740, 960),
    media_kind: "reel",
  },
  {
    post_id: "web:edinburgh",
    post_url: "https://example.com/edinburgh-closes",
    platform: "web",
    caption: "Edinburgh closes and courtyards\nHidden stairs between the Royal Mile and Grassmarket.",
    hashtags: ["scotland", "walking"],
    author_handle: "haar.walk",
    posted_at: "2025-10-30T14:00:00Z",
    place_names: ["Edinburgh"],
    place_ids: ["p-edi"],
    thumbnail_url: thumbs("edinburgh", 880, 660),
    media_kind: "article",
  },
  {
    post_id: "tiktok:sydney",
    post_url: "https://www.tiktok.com/@demo/video/22",
    platform: "tiktok",
    caption: "Bondi to Coogee coastal walk\nOcean pools, cliffs, and a flat white reward.",
    hashtags: ["sydney", "coast"],
    author_handle: "harbour.pace",
    posted_at: "2026-02-20T01:00:00Z",
    place_names: ["Bondi", "Sydney"],
    place_ids: ["p-bondi", "p-sydney"],
    thumbnail_url: thumbs("sydney", 720, 1280),
    media_kind: "video",
  },
  {
    post_id: "instagram:fez",
    post_url: "https://www.instagram.com/reel/demo23/",
    platform: "instagram",
    caption: "Fez tanneries from above\nColor pits, rooftop mint tea, maze exits.",
    hashtags: ["morocco", "medina"],
    author_handle: "souk.soft",
    posted_at: "2025-11-11T10:00:00Z",
    place_names: ["Fez"],
    place_ids: ["p-fez"],
    thumbnail_url: thumbs("fez", 720, 940),
    media_kind: "reel",
  },
  {
    post_id: "youtube:oslo",
    post_url: "https://www.youtube.com/watch?v=demo24",
    platform: "youtube",
    caption: "Oslo fjord day with a museum stop\nOpera roof walk, then Munch, then fish soup.",
    hashtags: ["norway", "city"],
    author_handle: "fjord.frame",
    posted_at: "2025-08-28T09:00:00Z",
    place_names: ["Oslo"],
    place_ids: ["p-oslo"],
    thumbnail_url: thumbs("oslo", 1280, 720),
    media_kind: "video",
  },
];
