const paths=[
  ["Asia","Japan","Kansai","Kyoto","Fushimi Inari"],["Asia","Japan","Kansai","Kyoto","Nishiki Market"],["Asia","Japan","Kanto","Tokyo","Meiji Jingu"],["Asia","Thailand","Chiang Mai","Old City","Doi Suthep"],
  ["Europe","Italy","Campania","Agerola","Path of the Gods"],["Europe","Italy","Veneto","Cortina","Lago di Sorapis"],["Europe","Portugal","Lisboa","Lisbon","Alfama"],["Europe","Portugal","Norte","Porto","Cais da Ribeira"],
  ["North America","United States","California","Big Sur","McWay Falls"],["North America","United States","New York","New York City","The High Line"]
];
const levels=["World","Continent","Country","Region","City","Place"];
function node(name,depth,parent=null){return{name,depth,parent,children:[],count:0,key:parent?`${parent.key}/${name}`:"World"}}
const root=node("World",0);const index=new Map([[root.key,root]]);
paths.forEach(path=>{let cur=root;cur.count++;path.forEach((name,i)=>{let next=cur.children.find(c=>c.name===name);if(!next){next=node(name,i+1,cur);cur.children.push(next);index.set(next.key,next)}next.count++;cur=next})});
const concepts=[
 ["01","constellation","Destination constellation","Child destinations orbit the current place like discoverable stars."],
 ["02","portal","Nested worlds","Every selection opens a deeper framed world without losing the worlds behind it."],
 ["03","metro","Geography metro","The current path is a transit line; sibling destinations become transfer branches."],
 ["04","passport","Living passport","Countries, regions, and cities accumulate as stamps across a travel document."],
 ["05","shelf","Atlas bookshelf","Geographies become volumes; cities and places become chapters worth pulling out."],
 ["06","sentence","Geographic sentence","Navigation becomes a sentence that rewrites itself as the destination sharpens."],
 ["07","solar","Destination solar system","Scale and depth become nested orbital relationships around the current scope."],
 ["08","film","Travel filmstrip","Each geographic rung is a scene; drilling feels like advancing a visual story."],
 ["09","strata","Cartographic strata","Ancestor layers remain physically stacked beneath the active geography."],
 ["10","dialogue","Atlas conversation","The hierarchy behaves like a guided dialogue instead of a navigation control."],
];
const state=new Map(concepts.map(([,slug])=>[slug,root.key]));const grid=document.querySelector("#grid");const toast=document.querySelector("#toast");let timer;
const icon=(name,size=15)=>`<i data-lucide="${name}" width="${size}" height="${size}"></i>`;
const trail=n=>{const list=[];let cur=n;while(cur){list.unshift(cur);cur=cur.parent}return list};
const child=n=>`<button type="button" data-key="${n.key}"><small>${levels[n.depth]}</small><b>${n.name}</b><span>${n.count}</span></button>`;
const arrival=n=>`<div class="arrival">${icon("map-pin",22)}<small>You found a place</small><b>${n.name}</b><span>${trail(n).slice(1,-1).map(x=>x.name).join(" · ")}</span><button data-open="${n.name}" type="button">Open details</button></div>`;
const renderers={
 constellation:n=>`<div class="cosmos"><div class="starfield"></div><button class="north" data-key="World" type="button">N</button><div class="cosmos-core"><small>${levels[n.depth]}</small><b>${n.name}</b><span>${n.count} places</span></div>${n.children.length?n.children.slice(0,6).map((c,i)=>`<button class="star star-${i+1}" data-key="${c.key}" type="button"><i></i><b>${c.name}</b><small>${c.count}</small></button>`).join(""):arrival(n)}<div class="cosmos-trail">${trail(n).map(x=>`<button data-key="${x.key}" type="button">${x.name}</button>`).join(" · ")}</div></div>`,
 portal:n=>`<div class="portal-world"><div class="portal-stack">${trail(n).slice(-4).map((x,i,a)=>`<button class="portal-frame frame-${i}" style="--frame:${i};--frames:${a.length}" data-key="${x.key}" type="button"><span>${levels[x.depth]}</span><b>${x.name}</b></button>`).join("")}</div>${n.children.length?`<div class="portal-choices"><span>Enter</span>${n.children.map(child).join("")}</div>`:arrival(n)}</div>`,
 metro:n=>{const t=trail(n);return `<div class="metro-map"><header><span>GEO</span><b>${n.name} line</b><small>${n.count} saved places</small></header><div class="main-line">${t.map((x,i)=>`<button data-key="${x.key}" type="button"><i>${i+1}</i><span>${levels[x.depth]}</span><b>${x.name}</b></button>`).join("")}</div>${n.children.length?`<div class="transfer"><span>Transfer to ${levels[n.depth+1]}</span>${n.children.map((c,i)=>`<button data-key="${c.key}" type="button"><i style="--color:${["#ef7054","#3c8b72","#7b61d1"][i%3]}"></i><b>${c.name}</b><small>${c.count} stops</small></button>`).join("")}</div>`:arrival(n)}</div>`},
 passport:n=>`<div class="passport"><div class="binding"></div><section class="passport-left"><span class="passport-mark">W</span><small>PLACE PASSPORT</small><b>${n.name}</b><p>${n.count} places held inside this geography.</p><div class="visa-line">${trail(n).map(x=>`<button data-key="${x.key}" type="button">${x.name}</button>`).join(" / ")}</div></section><section class="passport-right">${n.children.length?n.children.map((c,i)=>`<button class="stamp stamp-${i+1}" data-key="${c.key}" type="button"><small>${levels[c.depth]}</small><b>${c.name}</b><span>${c.count}</span></button>`).join(""):arrival(n)}</section></div>`,
 shelf:n=>`<div class="library"><header><span>THE LIVING ATLAS</span><b>${n.name}</b><small>Volume ${n.depth+1} of 6</small></header><div class="shelf-shadow"></div>${n.children.length?`<div class="books">${n.children.map((c,i)=>`<button class="book book-${i%5}" data-key="${c.key}" type="button"><span>${levels[c.depth]}</span><b>${c.name}</b><small>${c.count} chapters</small></button>`).join("")}</div>`:arrival(n)}<nav>${trail(n).map(x=>`<button data-key="${x.key}" type="button">${x.name}</button>`).join(" → ")}</nav></div>`,
 sentence:n=>`<div class="sentence-world"><p class="sentence-kicker">Your atlas says</p><div class="big-sentence">${trail(n).map((x,i)=>`<span>${i?['contains','opens into','narrows toward','arrives at','reveals'][i-1]:''} <button data-key="${x.key}" type="button">${x.name}</button></span>`).join("")}</div>${n.children.length?`<div class="sentence-choices"><small>Finish the next phrase</small>${n.children.map(c=>`<button data-key="${c.key}" type="button">${c.name}<sup>${c.count}</sup></button>`).join("")}</div>`:arrival(n)}</div>`,
 solar:n=>`<div class="solar-system"><div class="orbit o1"></div><div class="orbit o2"></div><div class="sun-core"><small>${levels[n.depth]}</small><b>${n.name}</b><span>${n.count}</span></div>${n.children.length?n.children.slice(0,6).map((c,i)=>`<button class="planet planet-${i+1}" data-key="${c.key}" type="button"><i></i><b>${c.name}</b><small>${c.count}</small></button>`).join(""):arrival(n)}<nav>${trail(n).map(x=>`<button data-key="${x.key}" type="button">${x.name}</button>`).join(" / ")}</nav></div>`,
 film:n=>`<div class="film-world"><div class="film-title"><span>SCENE ${String(n.depth+1).padStart(2,'0')}</span><b>${n.name}</b><small>${levels[n.depth]} · ${n.count} places</small></div><div class="filmstrip">${n.children.length?n.children.map((c,i)=>`<button class="frame image-${i%3}" data-key="${c.key}" type="button"><i>${String(i+1).padStart(2,'0')}</i><span>${levels[c.depth]}</span><b>${c.name}</b></button>`).join(""):arrival(n)}</div><div class="film-path">${trail(n).map(x=>`<button data-key="${x.key}" type="button">${x.name}</button>`).join(" — ")}</div></div>`,
 strata:n=>`<div class="strata-world"><div class="strata-stack">${trail(n).slice(-5).map((x,i,a)=>`<button style="--layer:${i};--layers:${a.length}" data-key="${x.key}" type="button"><small>${levels[x.depth]}</small><b>${x.name}</b><span>${x.count}</span></button>`).join("")}</div>${n.children.length?`<div class="strata-next"><small>Lift the next layer</small>${n.children.map(child).join("")}</div>`:arrival(n)}</div>`,
 dialogue:n=>`<div class="chat-atlas"><header>${icon("sparkles",16)}<span><b>Atlas</b><small>Knows your saved world</small></span></header><div class="messages"><p>Where would you like to explore?</p>${trail(n).slice(1).map((x,i)=>`<p class="user">${i?`Take me into ${x.name}`:`Show me ${x.name}`}</p><p>${i===trail(n).length-2?`${levels[x.depth]} selected. ${x.count} places here.`:`Opening ${x.name}…`}</p>`).join("")}</div>${n.children.length?`<div class="replies"><small>Suggested replies</small>${n.children.map(c=>`<button data-key="${c.key}" type="button">${icon("corner-down-right",12)} Explore ${c.name}<span>${c.count}</span></button>`).join("")}</div>`:arrival(n)}</div>`
};
function render(slug){const n=index.get(state.get(slug))||root;const el=grid.querySelector(`[data-stage="${slug}"]`);el.innerHTML=renderers[slug](n);lucide.createIcons()}
grid.innerHTML=concepts.map(([id,slug,name,note])=>`<article class="demo" data-demo="${slug}"><header><span>${id}</span><div><h3>${name}</h3><p>${note}</p></div><button data-reset type="button">${icon("rotate-ccw",14)}</button></header><div class="stage concept-${slug}" data-stage="${slug}"></div></article>`).join("");concepts.forEach(([,s])=>render(s));
function notify(text){clearTimeout(timer);toast.textContent=text;toast.hidden=false;timer=setTimeout(()=>toast.hidden=true,1500)}
grid.addEventListener("click",e=>{const demo=e.target.closest("[data-demo]");if(!demo)return;const slug=demo.dataset.demo;if(e.target.closest("[data-reset]")){state.set(slug,root.key);render(slug);return}const target=e.target.closest("[data-key]");if(target){state.set(slug,target.dataset.key);render(slug);return}const open=e.target.closest("[data-open]");if(open)notify(`${open.dataset.open} detail would open`)});document.querySelector("#reset").addEventListener("click",()=>{concepts.forEach(([,s])=>{state.set(s,root.key);render(s)});notify("Every world reset")});
